using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using static Content.Shared._WF.ShuttleShunter.Components.ShuttleShunterComponent;

namespace Content.Client._WF.ShuttleShunter.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleShunterWindow : DefaultWindow
{
    public event Action? OnShunt;

    public ShuttleShunterWindow()
    {
        RobustXamlLoader.Load(this);
        ShuntButton.OnPressed += _ => OnShunt?.Invoke();
    }

    public void UpdateState(ShuttleShunterBoundUserInterfaceState state)
    {
        ShuttleNameLabel.Text = state.ShuttleName;
        ShuttleOwnerLabel.Text = state.ShuttleOwner;
        ShuttleValueLabel.Text = Loc.GetString("shuttle-shunter-value-display", ("value", state.AppraisalValue));
    }
}
