using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Floof.Vore;

[GenerateTypedNameReferences]
public sealed partial class CustomVoreWindow : FancyWindow
{
    public Action<CustomVoreSubmitData>? OnGo;

    private CustomVorePresetState _state = new();
    private bool _loading;

    public CustomVoreWindow()
    {
        RobustXamlLoader.Load(this);

        PresetSelector.OnItemSelected += OnPresetSelected;
        EmoteLineEdit.PlaceHolder = Loc.GetString("vore-custom-window-emote-placeholder");
        DigestionLineEdit.PlaceHolder = Loc.GetString("vore-custom-window-digestion-placeholder");
        EmoteLineEdit.OnTextChanged += _ => UpdateGoButton();

        CancelButton.OnPressed += _ => Close();
        GoButton.OnPressed += _ => Confirm();

        LoadPresets();

        UpdateGoButton();
    }

    public void SetTargetName(string targetName)
    {
        TargetLabel.Text = Loc.GetString("vore-custom-window-target", ("target", targetName));
    }

    public void SetDigestAllowed(bool allowed)
    {
        AllowDigestionCheckBox.Disabled = !allowed;
        if (!allowed)
        {
            AllowDigestionCheckBox.Pressed = false;
            AllowDigestionCheckBox.ToolTip = Loc.GetString("vore-custom-window-digestion-disabled");
        }
        else
        {
            AllowDigestionCheckBox.ToolTip = string.Empty;
        }
    }

    private void LoadPresets()
    {
        _loading = true;
        _state = CustomVoreSettingsStore.Load();

        PresetSelector.Clear();
        for (var i = 0; i < _state.Presets.Count; i++)
            PresetSelector.AddItem(CustomVoreSettingsStore.GetDisplayName(_state.Presets[i], i), i);

        ApplyPreset(Math.Clamp(_state.SelectedPresetIndex, 0, _state.Presets.Count - 1));
        _loading = false;
    }

    private void OnPresetSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_loading)
            return;

        ApplyPreset(args.Id);
    }

    private void ApplyPreset(int index)
    {
        if (_state.Presets.Count == 0)
            return;

        _loading = true;
        var preset = _state.Presets[Math.Clamp(index, 0, _state.Presets.Count - 1)];
        _state.SelectedPresetIndex = Math.Clamp(index, 0, _state.Presets.Count - 1);

        EmoteLineEdit.Text = preset.CustomEmote;
        DigestionLineEdit.Text = preset.CustomDigestionEmote;
        StomachSoundsCheckBox.Pressed = preset.PlayStomachSounds;
        AllowDigestionCheckBox.Pressed = preset.AllowDigestion;
        PresetSelector.SelectId(_state.SelectedPresetIndex);
        _loading = false;
    }

    private void Confirm()
    {
        var emote = EmoteLineEdit.Text.Trim();
        if (string.IsNullOrWhiteSpace(emote))
            return;

        OnGo?.Invoke(new CustomVoreSubmitData(emote, DigestionLineEdit.Text.Trim(), StomachSoundsCheckBox.Pressed, AllowDigestionCheckBox.Pressed));
        Close();
    }

    private void UpdateGoButton()
    {
        GoButton.Disabled = string.IsNullOrWhiteSpace(EmoteLineEdit.Text);
    }
}

public readonly record struct CustomVoreSubmitData(string CustomEmote, string CustomDigestionEmote, bool PlayStomachSounds, bool AllowDigestion);