using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class WayfarerTab : Control
{
    private WayfarerCustomVoreWindow? _customVoreWindow;

    public WayfarerTab()
    {
        RobustXamlLoader.Load(this);
        CustomVoreButton.OnPressed += _ => OpenCustomVoreWindow();
    }

    public void ReloadValues()
    {
        _customVoreWindow?.ReloadValues();
    }

    private void OpenCustomVoreWindow()
    {
        if (_customVoreWindow == null || _customVoreWindow.Disposed)
            _customVoreWindow = new WayfarerCustomVoreWindow();

        _customVoreWindow.ReloadValues();
        _customVoreWindow.OpenCentered();
    }
}