using Content.Client._Floof.Vore;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;

namespace Content.Client._WF.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class WayfarerCustomVoreWindow : FancyWindow
{
    private CustomVorePresetState _state = new();
    private bool _loading;
    private bool _dirty;

    public WayfarerCustomVoreWindow()
    {
        RobustXamlLoader.Load(this);

        PresetSelector.OnItemSelected += OnPresetSelected;
        NicknameLineEdit.OnTextChanged += _ => MarkDirty();
        AttemptTextLineEdit.OnTextChanged += _ => MarkDirty();
        VoreTextLineEdit.OnTextChanged += _ => MarkDirty();
        DigestionTextLineEdit.OnTextChanged += _ => MarkDirty();
        PlayStomachSoundsCheckBox.OnToggled += _ => MarkDirty();
        AllowDigestionCheckBox.OnToggled += _ => MarkDirty();
        NewPresetButton.OnPressed += _ => AddPreset();
        DeletePresetButton.OnPressed += _ => DeletePreset();
        ReloadButton.OnPressed += _ => ReloadValues();
        SaveButton.OnPressed += _ => SaveValues();

        ReloadValues();
    }

    public void ReloadValues()
    {
        _loading = true;
        _state = CustomVoreSettingsStore.Load();
        PopulatePresetSelector();
        LoadPreset(_state.SelectedPresetIndex);
        _dirty = false;
        UpdateButtons();
        _loading = false;
    }

    private void OnPresetSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (_loading)
            return;

        SaveCurrentPreset();
        LoadPreset(args.Id);
        _state.SelectedPresetIndex = args.Id;
        _dirty = true;
        UpdateButtons();
    }

    private void AddPreset()
    {
        SaveCurrentPreset();

        var nextIndex = _state.Presets.Count + 1;
        _state.Presets.Add(new CustomVorePreset
        {
            Nickname = $"Preset {nextIndex}",
        });

        _state.SelectedPresetIndex = _state.Presets.Count - 1;
        PopulatePresetSelector();
        LoadPreset(_state.SelectedPresetIndex);
        _dirty = true;
        UpdateButtons();
    }

    private void DeletePreset()
    {
        if (_state.Presets.Count <= 1)
            return;

        _state.Presets.RemoveAt(_state.SelectedPresetIndex);
        _state.SelectedPresetIndex = Math.Clamp(_state.SelectedPresetIndex, 0, _state.Presets.Count - 1);

        PopulatePresetSelector();
        LoadPreset(_state.SelectedPresetIndex);
        _dirty = true;
        UpdateButtons();
    }

    private void SaveValues()
    {
        SaveCurrentPreset();
        CustomVoreSettingsStore.Save(_state);

        if (IoCManager.Resolve<IEntityManager>().TrySystem<CustomVoreSystem>(out var customVoreSystem))
            customVoreSystem.SyncPresetsToServer();

        _dirty = false;
        UpdateButtons();
    }

    private void SaveCurrentPreset()
    {
        if (_state.Presets.Count == 0 || _state.SelectedPresetIndex < 0 || _state.SelectedPresetIndex >= _state.Presets.Count)
            return;

        var preset = _state.Presets[_state.SelectedPresetIndex];
        preset.Nickname = NicknameLineEdit.Text.Trim();
        preset.CustomAttemptText = AttemptTextLineEdit.Text.Trim();
        preset.CustomEmote = VoreTextLineEdit.Text.Trim();
        preset.CustomDigestionEmote = DigestionTextLineEdit.Text.Trim();
        preset.PlayStomachSounds = PlayStomachSoundsCheckBox.Pressed;
        preset.AllowDigestion = AllowDigestionCheckBox.Pressed;
    }

    private void LoadPreset(int index)
    {
        if (_state.Presets.Count == 0)
            return;

        _loading = true;
        var clampedIndex = Math.Clamp(index, 0, _state.Presets.Count - 1);
        _state.SelectedPresetIndex = clampedIndex;

        var preset = _state.Presets[clampedIndex];
        NicknameLineEdit.Text = preset.Nickname;
        AttemptTextLineEdit.Text = preset.CustomAttemptText;
        VoreTextLineEdit.Text = preset.CustomEmote;
        DigestionTextLineEdit.Text = preset.CustomDigestionEmote;
        PlayStomachSoundsCheckBox.Pressed = preset.PlayStomachSounds;
        AllowDigestionCheckBox.Pressed = preset.AllowDigestion;

        PresetSelector.SelectId(clampedIndex);
        _loading = false;
    }

    private void PopulatePresetSelector()
    {
        PresetSelector.Clear();

        for (var i = 0; i < _state.Presets.Count; i++)
            PresetSelector.AddItem(CustomVoreSettingsStore.GetDisplayName(_state.Presets[i], i), i);
    }

    private void MarkDirty()
    {
        if (_loading)
            return;

        _dirty = true;
        UpdateButtons();
    }

    private void UpdateButtons()
    {
        SaveButton.Disabled = !_dirty;
        DeletePresetButton.Disabled = _state.Presets.Count <= 1;
        StatusLabel.Text = _dirty ? "Unsaved changes" : $"{_state.Presets.Count} presets saved";
    }
}