using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._WF.Outlaws.UI;

[GenerateTypedNameReferences]
public sealed partial class OutlawDisclaimerWindow : Control
{
    private const float CountdownSeconds = 10f;
    private float _remaining = CountdownSeconds;

    public event Action? OnAcknowledge;

    public OutlawDisclaimerWindow()
    {
        RobustXamlLoader.Load(this);
        AcknowledgeButton.Disabled = true;
        AcknowledgeButton.OnPressed += _ => OnAcknowledge?.Invoke();
        UpdateButtonText();
    }

    public void SetState(bool isWanted)
    {
        if (isWanted)
        {
            TitleLabel.Text = Loc.GetString("outlaw-disclaimer-title-wanted");
            var msg = new FormattedMessage();
            msg.AddMarkup(Loc.GetString("outlaw-disclaimer-message-wanted"));
            MessageLabel.SetMessage(msg);
        }
        else
        {
            TitleLabel.Text = Loc.GetString("outlaw-disclaimer-title");
            var msg = new FormattedMessage();
            msg.AddMarkup(Loc.GetString("outlaw-disclaimer-message"));
            MessageLabel.SetMessage(msg);
        }
    }

    private void UpdateButtonText()
    {
        if (_remaining > 0f)
            AcknowledgeButton.Text = Loc.GetString("outlaw-disclaimer-button-countdown", ("seconds", (int) MathF.Ceiling(_remaining)));
        else
            AcknowledgeButton.Text = Loc.GetString("outlaw-disclaimer-button");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!AcknowledgeButton.Disabled)
            return;

        _remaining -= args.DeltaSeconds;
        if (_remaining <= 0f)
        {
            _remaining = 0f;
            AcknowledgeButton.Disabled = false;
        }

        UpdateButtonText();
    }
}
