using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.RouletteTable.BUI;
using Content.Shared._WF.RouletteTable.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.IoC;

namespace Content.Client._WF.RouletteTable;

[GenerateTypedNameReferences]
public sealed partial class RouletteTableWindow : FancyWindow
{
    public event Action<RouletteBetType, int, int>? OnPlaceBet;
    public event Action? OnSpin;
    public event Action? OnClearMyBets;
    public event Action? OnCashOut;

    // Standard European roulette red numbers.
    private static readonly HashSet<int> RedNumbers = new()
    {
        1, 3, 5, 7, 9, 12, 14, 16, 18, 19, 21, 23, 25, 27, 30, 32, 34, 36
    };

    public RouletteTableWindow()
    {
        RobustXamlLoader.Load(this);
        BuildNumberGrid();
        BindOutsideBetButtons();
        BindControlButtons();
    }

    private void BuildNumberGrid()
    {
        // 0 button – green
        ZeroButton.ModulateSelfOverride = new Color(0.05f, 0.45f, 0.10f);
        ZeroButton.OnPressed += _ => PlaceBet(RouletteBetType.Number, 0);

        // Numbers 1-36 laid out in 3 rows x 12 columns.
        // Row 0 (top):    3, 6, 9, ..., 36
        // Row 1 (middle): 2, 5, 8, ..., 35
        // Row 2 (bottom): 1, 4, 7, ..., 34
        for (var row = 0; row < 3; row++)
        {
            for (var col = 0; col < 12; col++)
            {
                var number = 3 * (col + 1) - row;
                var isRed = RedNumbers.Contains(number);

                var btn = new Button
                {
                    Text = number.ToString(),
                    MinSize = new Vector2(32, 28),
                    Margin = new Thickness(1),
                    ModulateSelfOverride = isRed
                        ? new Color(0.75f, 0.15f, 0.15f)
                        : new Color(0.15f, 0.15f, 0.20f),
                };

                var capturedNumber = number;
                btn.OnPressed += _ => PlaceBet(RouletteBetType.Number, capturedNumber);
                NumberGrid.AddChild(btn);
            }
        }

        // Column 2-to-1 buttons (top row = col 3, middle = col 2, bottom = col 1)
        Col3Button.OnPressed += _ => PlaceBet(RouletteBetType.ColumnThird, 0);
        Col2Button.OnPressed += _ => PlaceBet(RouletteBetType.ColumnSecond, 0);
        Col1Button.OnPressed += _ => PlaceBet(RouletteBetType.ColumnFirst, 0);
    }

    private void BindOutsideBetButtons()
    {
        Dozen1Button.OnPressed += _ => PlaceBet(RouletteBetType.DozenFirst, 0);
        Dozen2Button.OnPressed += _ => PlaceBet(RouletteBetType.DozenSecond, 0);
        Dozen3Button.OnPressed += _ => PlaceBet(RouletteBetType.DozenThird, 0);

        LowButton.OnPressed   += _ => PlaceBet(RouletteBetType.Low, 0);
        EvenButton.OnPressed  += _ => PlaceBet(RouletteBetType.Even, 0);
        OddButton.OnPressed   += _ => PlaceBet(RouletteBetType.Odd, 0);
        HighButton.OnPressed  += _ => PlaceBet(RouletteBetType.High, 0);

        RedButton.ModulateSelfOverride   = new Color(0.75f, 0.15f, 0.15f);
        BlackButton.ModulateSelfOverride = new Color(0.15f, 0.15f, 0.20f);
        RedButton.OnPressed   += _ => PlaceBet(RouletteBetType.Red, 0);
        BlackButton.OnPressed += _ => PlaceBet(RouletteBetType.Black, 0);
    }

    private void BindControlButtons()
    {
        Bet100Button.OnPressed  += _ => BetAmountEdit.Text = "100";
        Bet500Button.OnPressed  += _ => BetAmountEdit.Text = "500";
        Bet1000Button.OnPressed += _ => BetAmountEdit.Text = "1000";
        Bet5000Button.OnPressed += _ => BetAmountEdit.Text = "5000";
        BetMaxButton.OnPressed  += _ => BetAmountEdit.Text = "10000";

        ClearMyBetsButton.OnPressed += _ => OnClearMyBets?.Invoke();
        SpinButton.OnPressed        += _ => OnSpin?.Invoke();
        CashOutButton.OnPressed     += _ => OnCashOut?.Invoke();
    }

    private void PlaceBet(RouletteBetType betType, int betValue)
    {
        if (!int.TryParse(BetAmountEdit.Text, out var amount) || amount <= 0 || amount > 10000)
            return;

        OnPlaceBet?.Invoke(betType, betValue, amount);
    }

    public void UpdateState(RouletteTableBUIState state)
    {
        // Look up the local player's entity to find their table balance.
        var entityManager = IoCManager.Resolve<IEntityManager>();
        var playerManager = IoCManager.Resolve<Robust.Client.Player.IPlayerManager>();
        var localEntity = playerManager.LocalEntity;
        var myBalance = 0;
        if (localEntity.HasValue)
        {
            var netSelf = entityManager.GetNetEntity(localEntity.Value);
            state.TableBalances.TryGetValue(netSelf, out myBalance);
        }

        TableBalanceLabel.Text = $"{myBalance:N0} ₮";
        CashOutButton.Disabled = state.IsSpinning || myBalance <= 0;

        SpinButton.Disabled = state.IsSpinning || state.Bets.Count == 0;
        SpinButton.Text = state.IsSpinning
            ? Loc.GetString("roulette-spinning")
            : Loc.GetString("roulette-spin");

        ClearMyBetsButton.Disabled = state.IsSpinning;

        if (state.LastResult.HasValue)
        {
            var result = state.LastResult.Value;
            string color;
            if (result == 0)
                color = Loc.GetString("roulette-color-green");
            else if (RedNumbers.Contains(result))
                color = Loc.GetString("roulette-color-red");
            else
                color = Loc.GetString("roulette-color-black");

            LastResultLabel.Text = Loc.GetString("roulette-last-result", ("number", result), ("color", color));
        }
        else
        {
            LastResultLabel.Text = Loc.GetString("roulette-no-result");
        }

        BetsList.DisposeAllChildren();
        foreach (var bet in state.Bets)
        {
            var betLabel = BetTypeToString(bet.BetType, bet.BetValue);
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label
            {
                Text = $"{bet.PlayerName}: {betLabel} — {bet.Amount}₮",
                HorizontalExpand = true,
                ClipText = true,
            });
            BetsList.AddChild(row);
        }
    }

    private static string BetTypeToString(RouletteBetType betType, int betValue)
    {
        return betType switch
        {
            RouletteBetType.Number       => $"#{betValue}",
            RouletteBetType.Red          => "Red",
            RouletteBetType.Black        => "Black",
            RouletteBetType.Odd          => "Odd",
            RouletteBetType.Even         => "Even",
            RouletteBetType.Low          => "1-18",
            RouletteBetType.High         => "19-36",
            RouletteBetType.DozenFirst   => "1st 12",
            RouletteBetType.DozenSecond  => "2nd 12",
            RouletteBetType.DozenThird   => "3rd 12",
            RouletteBetType.ColumnFirst  => "Col 1",
            RouletteBetType.ColumnSecond => "Col 2",
            RouletteBetType.ColumnThird  => "Col 3",
            _                            => "?",
        };
    }
}
