using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._WF.Corporations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Corporations;

[GenerateTypedNameReferences]
public sealed partial class CorporationAtmMenu : FancyWindow
{
    public event Action<int>? DepositRequest;
    public event Action<int>? WithdrawRequest;

    private int _corpId = -1;

    public CorporationAtmMenu()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("corp-atm-title");
        DepositButton.OnPressed += _ => Invoke(DepositRequest);
        WithdrawButton.OnPressed += _ => Invoke(WithdrawRequest);
    }

    public void UpdateState(CorporationAtmUiState state)
    {
        _corpId = state.CorporationId;
        var hasCorp = state.CorporationName != null;

        CorpNameLabel.Text = hasCorp
            ? state.CorporationName!
            : Loc.GetString("corp-atm-no-corp");

        CorpBalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        PlayerBalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.PlayerBalance);

        StatusLabel.Text = string.IsNullOrEmpty(state.StatusMessage)
            ? string.Empty
            : Loc.GetString(state.StatusMessage);

        DepositButton.Disabled = !hasCorp;
        WithdrawButton.Disabled = !hasCorp || !state.CanWithdraw;
    }

    private void Invoke(Action<int>? action)
    {
        if (int.TryParse(AmountEdit.Text, out var amount) && amount > 0)
            action?.Invoke(amount);
    }
}
